# rectangle formation yaml
# global goal setting
global_goal:
  swarm_central_pos: {x: 25.0, y: 0.0, z: 1.0}
  swarm_scale : 2.5
  relative_pos_s10: {x: 0.000, y: 0.00, z: 0.0}
  relative_pos_s11: {x: 0.8000, y: 0.7500, z: 0.0}
  relative_pos_s12: {x: 0.0000, y: 1.5200, z: 0.0}
  relative_pos_s13: {x: -0.7600, y: 0.7300, z: 0.0}
  relative_pos_s14: {x: 0.7700, y: -0.7600, z: 0.0}
  relative_pos_s15: {x: 0.0000, y: -1.4900, z: 0.0}
  relative_pos_s16: {x: -0.7600, y: -0.7500, z: 0.0}

  relative_pos_y0: {x: -0.4900, y: 0.5100, z: 0.0}
  relative_pos_y1: {x: 0.5000, y: 0.5000, z: 0.0}
  relative_pos_y2: {x: 1.0200, y: 1.0200, z: 0.0}
  relative_pos_y3: {x: -1.0000, y: 1.0300, z: 0.0}
  relative_pos_y4: {x: 0.0000, y: -0.6800, z: 0.0}
  relative_pos_y5: {x: 0.0000, y: -1.4700, z: 0.0}
  relative_pos_y6: {x: 0.000, y: 0.00, z: 0.0}

  relative_pos_s20: {x: 0.000, y: 0.00, z: 0.0}
  relative_pos_s21: {x: 0.8000, y: 0.7500, z: 0.0}
  relative_pos_s22: {x: 0.0000, y: 1.5200, z: 0.0}
  relative_pos_s23: {x: -0.7600, y: 0.7300, z: 0.0}
  relative_pos_s24: {x: -0.7600, y: -0.7500, z: 0.0}
  relative_pos_s25: {x: 0.0000, y: -1.4900, z: 0.0}
  relative_pos_s26: {x: 0.7700, y: -0.7600, z: 0.0}
  

  relative_pos_u0: {x: -1.0000, y: 0.4800, z: 0.0}
  relative_pos_u1: {x: 0.9800, y: 0.5100, z: 0.0}
  relative_pos_u2: {x: 1.0100, y: 1.5300, z: 0.0}
  relative_pos_u3: {x: -0.9800, y: 1.5200, z: 0.0}
  relative_pos_u4: {x: 0.8500, y: -1.0000, z: 0.0}
  relative_pos_u5: {x: 0.0200, y: -1.2400, z: 0.0}
  relative_pos_u6: {x: -0.7600, y: -1.0000, z: 0.0}



# map_size_x          : 70.0
# map_size_y          : 30.0
# map_size_z          : 3.0
optimization:
  formation_type      : 1
  weight_obstacle     : 50000.0
  weight_swarm        : 50000.0
  weight_feasibility  : 10000.0
  weight_sqrvariance  : 10000.0
  weight_time         : 80.0
  weight_formation    : 15000.0
  obstacle_clearance  : 0.5
  swarm_clearance     : 0.5

fsm:
  replan_trajectory_time : 0.1    # s, the max time of replanning trajectory