# rectangle formation yaml
# global goal setting
global_goal:
  swarm_central_pos: {x: 25.0, y: 0.0, z: 1.0}
  swarm_scale : 4
  relative_pos_s0: {x: 0.000, y: 0.00, z: 0.0}
  relative_pos_s1: {x: 0.8825, y: 0.7274, z: 0.0}
  relative_pos_s2: {x: -0.0104, y: 1.5182, z: 0.0}
  relative_pos_s3: {x: -0.7652, y: 0.7358, z: 0.0}
  relative_pos_s4: {x: 0.7694, y: -0.7291, z: 0.0}
  relative_pos_s5: {x: -0.0021, y: -1.4949, z: 0.0}
  relative_pos_s6: {x: -0.7652, y: -0.7474, z: 0.0}

  relative_pos_y0: {x: -0.4815, y: 0.5139, z: 0.0}
  relative_pos_y1: {x: 0.5156, y: 0.5122, z: 0.0}
  relative_pos_y2: {x: 1.0182, y: 1.0161, z: 0.0}
  relative_pos_y3: {x: -1.0058, y: 1.0277, z: 0.0}
  relative_pos_y4: {x: -0.0021, y: -0.6774, z: 0.0}
  relative_pos_y5: {x: 0.0062, y: -1.2715, z: 0.0}
  relative_pos_y6: {x: 0.000, y: 0.300, z: 0.0}
  

  relative_pos_u0: {x: -0.9975, y: 0.4788, z: 0.0}
  relative_pos_u1: {x: 0.9850, y: 0.5139, z: 0.0}
  relative_pos_u2: {x: 1.0099, y: 1.5299, z: 0.0}
  relative_pos_u3: {x: -0.9809, y: 1.5182, z: 0.0}
  relative_pos_u4: {x: 0.8523, y: -0.9927, z: 0.0}
  relative_pos_u5: {x: 0.0228, y: -1.2080, z: 0.0}
  relative_pos_u6: {x: -0.7569, y: -0.9927, z: 0.0}


# map_size_x          : 70.0
# map_size_y          : 30.0
# map_size_z          : 3.0
optimization:
  formation_type      : 1
  weight_obstacle     : 50000.0
  weight_swarm        : 50000.0
  weight_feasibility  : 10000.0
  weight_sqrvariance  : 10000.0
  weight_time         : 80.0
  weight_formation    : 15000.0
  obstacle_clearance  : 0.5
  swarm_clearance     : 0.5

fsm:
  replan_trajectory_time : 0.1    # s, the max time of replanning trajectory